servers:
  web:
    - <%= ENV["TEST_HOST"] %>

proxy:
  ssl: false
  host: <%= ENV["TEST_DOMAIN"] %>

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - DEVISE_JWT_SECRET_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

accessories:
  test-db:
    image: postgres:16-alpine
    host: <%= ENV["TEST_HOST"] %>
    port: "127.0.0.1:5434:5432"
    env:
      clear:
        POSTGRES_USER: backend
        POSTGRES_DB: backend_test_env
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
