name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy to staging.lifeos.kaizendevs.com
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: backend
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          DEPLOY_HOST: 127.0.0.1
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_STAGING }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
          DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY_STAGING }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_STAGING }}
          APP_VERSION: ${{ github.sha }}
        run: bundle exec kamal deploy -d staging
