name: Deploy to Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: true
        default: main

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.branch }} to test.lifeos.kaizendevs.com
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy
        working-directory: backend
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          DEPLOY_HOST: 127.0.0.1
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
          DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
          APP_VERSION: ${{ github.sha }}
        run: bundle exec kamal deploy -d test
