name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Type "production" to confirm
        required: true

jobs:
  deploy:
    name: Deploy to lifeos.kaizendevs.com
    runs-on: self-hosted
    if: github.event.inputs.confirm == 'production'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: backend
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          DEPLOY_HOST: 127.0.0.1
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          APP_VERSION: ${{ github.ref_name }}
        run: |
          export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
          bundle install --quiet
          bundle exec kamal deploy
